services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: loan-calculator-app
    restart: unless-stopped
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - pnpm_modules:/app/node_modules
    command: >
      sh -c "echo '[app] installing dependencies...' &&
      pnpm install &&
      echo '[app] starting nuxt dev server...' &&
      pnpm run dev"

volumes:
  pnpm_modules:
